fn main() {
    ::windows::build!(
        Windows::Win32::Direct2D::*,
        Windows::Win32::DisplayDevices::RECT,
        Windows::Win32::Gdi::{HBRUSH, UpdateWindow},
        Windows::Win32::MenusAndResources::{ HCURSOR, HICON },
        Windows::Win32::SystemServices::{ GetModuleHandleW, HINSTANCE },
        Windows::Foundation::Numerics::Matrix3x2,
        Windows::Win32::WindowsAndMessaging::{
            CREATESTRUCTW,
            CW_USEDEFAULT,
            CreateWindowExW,
            DefWindowProcW,
            DispatchMessageW,
            GetClientRect,
            GetWindowLongW,
            HWND,
            LPARAM,
            MSG,
            PeekMessageW,
            PostQuitMessage,
            RegisterClassW,
            SetWindowLongW,
            ShowWindow,
            TranslateMessage,
            WINDOW_EX_STYLE,
            WINDOW_LONG_PTR_INDEX,
            WINDOW_STYLE,
            WM_NCCREATE ,
            WM_DESTROY,
            WM_KEYDOWN,
            WM_PAINT,
            WM_QUIT,
            WNDCLASSW,
            WNDCLASS_STYLES,
            WPARAM,
            WM_CREATE,
        },
    );
}